"""Hosted Agntz client package."""

from .client import AgntzClient, AsyncAgntzClient
from .errors import AgntzError, AuthenticationError, NotFoundError, StreamError
from .models import (
    AgentDefinition,
    AgentListEntry,
    AgentVersionSummary,
    ApiKeyRecord,
    EvalCaseResult,
    EvalCriterion,
    EvalCriterionResult,
    EvalDataset,
    EvalDatasetItem,
    EvalDefinition,
    EvalLatestScore,
    EvalRun,
    EvalRunListResult,
    EvalRunSummary,
    Event,
    HealthResult,
    ModelConfig,
    Reply,
    Run,
    RunListResult,
    RunResult,
    TraceDetail,
)

__all__ = [
    "AgntzClient",
    "AgntzError",
    "AgentDefinition",
    "AgentListEntry",
    "AgentVersionSummary",
    "AsyncAgntzClient",
    "AuthenticationError",
    "ApiKeyRecord",
    "EvalCaseResult",
    "EvalCriterion",
    "EvalCriterionResult",
    "EvalDataset",
    "EvalDatasetItem",
    "EvalDefinition",
    "EvalLatestScore",
    "EvalRun",
    "EvalRunListResult",
    "EvalRunSummary",
    "Event",
    "HealthResult",
    "ModelConfig",
    "NotFoundError",
    "Reply",
    "Run",
    "RunListResult",
    "RunResult",
    "StreamError",
    "TraceDetail",
]
