import type { Capability, ProviderModelEntry } from "./types.js";

export const ALL_CAPABILITIES: readonly Capability[] = [
	"text",
	"multiTurn",
	"systemPrompt",
	"streaming",
	"tools",
	"parallelTools",
	"streamingTools",
	"toolChoice",
	"multimodalImage",
	"structuredOutput",
	"reasoning",
	"cancellation",
];

const caps = (...c: Capability[]): ReadonlySet<Capability> => new Set(c);

// OpenRouter subset — 8 family-representative routes (plan §08). Validates
// OpenRouter's pass-through across model families without testing every route.
// Capabilities are best-effort per underlying family; the first run with a real
// OPENROUTER_API_KEY is the verification.
const OPENROUTER_ROUTES: readonly ProviderModelEntry[] = [
	{
		provider: "openrouter",
		model: "anthropic/claude-opus-5",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Claude family via OpenRouter.",
	},
	{
		provider: "openrouter",
		model: "openai/gpt-5.6-sol",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "OpenAI family via OpenRouter.",
	},
	{
		provider: "openrouter",
		model: "google/gemini-3.6-flash",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Gemini family via OpenRouter.",
	},
	{
		provider: "openrouter",
		model: "meta-llama/llama-4-maverick",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"cancellation",
		),
		notes:
			"Maverick via OpenRouter supports single tool calls in runtime harness, but not reliable parallel tool calls (harness run 2026-06-03).",
	},
	{
		provider: "openrouter",
		model: "mistralai/mistral-medium-3-5",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes:
			"Mistral family via OpenRouter (slug uses hyphens: mistral-medium-3-5).",
	},
	{
		provider: "openrouter",
		model: "deepseek/deepseek-v4-pro",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes:
			"DeepSeek family via OpenRouter; tool caps confirmed by harness run 2026-05-23.",
	},
	{
		provider: "openrouter",
		model: "qwen/qwen3.8-max",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes:
			"Current Qwen flagship via OpenRouter; multimodal, reasoning, tools, and structured output are declared by the live catalog.",
	},
	{
		provider: "openrouter",
		model: "meta-llama/llama-4-scout",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"cancellation",
		),
		notes:
			"Fast/cheap Llama 4 via OpenRouter; tool caps confirmed by harness run 2026-05-23.",
	},
];

// Secondary models — an earlier or lower-cost current route per provider, so the
// harness catches SDK regressions that only surface on different model surfaces
// (finish-reason shapes, tool schemas, multimodal handling, etc.).
// IDs and caps are best-effort from the app's model catalog (supported-providers.ts);
// the first live run confirms availability and flips any wrong capability cell.
const SECONDARY_MODELS: readonly ProviderModelEntry[] = [
	{
		provider: "anthropic",
		model: "claude-opus-4-8",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Prior gen of claude-opus-5; still available on the Claude API.",
	},
	{
		provider: "openai",
		model: "gpt-5.5",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Prior gen of gpt-5.6-sol.",
	},
	{
		provider: "google",
		model: "gemini-3.5-flash",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Prior stable Flash generation; current counterpart is 3.6 Flash.",
	},
	{
		provider: "mistral",
		model: "mistral-large-2512",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"cancellation",
		),
		notes: "Earlier still-current general-purpose Mistral route.",
	},
	{
		provider: "groq",
		model: "openai/gpt-oss-20b",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes: "Efficient current Groq production route; text-only.",
	},
	{
		provider: "cohere",
		model: "command-a-03-2025",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"cancellation",
		),
		notes:
			"Prior gen of command-a-plus-05-2026; predates the unified reasoning surface. Base64 image path confirmed by runtime harness 2026-06-03.",
	},
];

// Cells are best-effort declarations pending verification by the harness itself.
// Capabilities that the planning doc marked as uncertain are included optimistically;
// the first run will surface anything that needs to flip via UNEXPECTED_UNSUPPORTED.

export const MATRIX: readonly ProviderModelEntry[] = [
	{
		provider: "anthropic",
		model: "claude-opus-5",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
	},
	{
		provider: "openai",
		model: "gpt-5.6-sol",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
	},
	{
		provider: "google",
		model: "gemini-3.6-flash",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
		notes: "Current stable Gemini workhorse model.",
	},
	{
		provider: "mistral",
		model: "mistral-medium-3-5",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
		notes:
			"multimodalImage confirmed by harness run 2026-05-23 (matrix was too conservative).",
	},
	{
		provider: "groq",
		model: "openai/gpt-oss-120b",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
		notes: "Current flagship Groq production route; text-only.",
	},
	{
		provider: "cohere",
		model: "command-a-plus-05-2026",
		capabilities: new Set<Capability>([
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"structuredOutput",
			"reasoning",
			"cancellation",
		]),
		notes:
			"Command A+ text/tool/structured/reasoning route; base64 image path returned empty in runtime harness (2026-06-03).",
	},
	{
		provider: "xai",
		model: "grok-4.5",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"multimodalImage",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
	},
	{
		provider: "deepseek",
		model: "deepseek-v4-pro",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"tools",
			"parallelTools",
			"streamingTools",
			"toolChoice",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
	},
	{
		provider: "perplexity",
		model: "sonar-reasoning-pro",
		capabilities: caps(
			"text",
			"multiTurn",
			"systemPrompt",
			"streaming",
			"structuredOutput",
			"reasoning",
			"cancellation",
		),
		notes:
			"Sonar search/reasoning route; provider does not expose function tools.",
	},
	...SECONDARY_MODELS,
	...OPENROUTER_ROUTES,
];
