import type { Capability, ProviderModelEntry } from './types.js';

export const ALL_CAPABILITIES: readonly Capability[] = [
  'text',
  'multiTurn',
  'systemPrompt',
  'streaming',
  'tools',
  'parallelTools',
  'streamingTools',
  'toolChoice',
  'multimodalImage',
  'structuredOutput',
  'reasoning',
  'cancellation',
];

// Cells are best-effort declarations pending verification by the harness itself.
// Capabilities that the planning doc marked as uncertain are included optimistically;
// the first run will surface anything that needs to flip via UNEXPECTED_UNSUPPORTED.

export const MATRIX: readonly ProviderModelEntry[] = [
  {
    provider: 'anthropic',
    model: 'claude-opus-4-7',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'multimodalImage',
      'structuredOutput',
      'reasoning',
      'cancellation',
    ]),
  },
  {
    provider: 'openai',
    model: 'gpt-5.5',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'multimodalImage',
      'structuredOutput',
      'reasoning',
      'cancellation',
    ]),
  },
  {
    provider: 'google',
    model: 'gemini-3.5-flash',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'multimodalImage',
      'structuredOutput',
      'reasoning',
      'cancellation',
    ]),
    notes: 'Pro variant delayed to June 2026; Flash is the available 3.5 entry point.',
  },
  {
    provider: 'mistral',
    model: 'mistral-medium-3.5',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'structuredOutput',
      'reasoning',
      'cancellation',
    ]),
    notes: 'Text-only — image support sits in Mistral Small 4 / Pixtral, not Medium.',
  },
  {
    provider: 'groq',
    model: 'llama-4-scout',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'multimodalImage',
      'structuredOutput',
      'cancellation',
    ]),
    notes: 'Llama 4 is natively multimodal; no extended-thinking surface exposed.',
  },
  {
    provider: 'cohere',
    model: 'command-a-plus',
    capabilities: new Set<Capability>([
      'text',
      'multiTurn',
      'systemPrompt',
      'streaming',
      'tools',
      'parallelTools',
      'streamingTools',
      'toolChoice',
      'multimodalImage',
      'structuredOutput',
      'reasoning',
      'cancellation',
    ]),
    notes: 'Command A+ unifies Command A / Vision / Reasoning / Translate (May 2026).',
  },
];
